{% set name = "isort" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/isort-{{ version }}.tar.gz
  sha256: 9b8f96a14cfee0677e78e941ff62f03769a06d412aabb9e2a90487b3b7e8d481

build:
  entry_points:
    - isort = isort.main:main
    - isort-identify-imports = isort.main:identify_imports_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - importlib-metadata >=4.6.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - isort
  commands:
    - pip check
    - isort --help
    - isort-identify-imports --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/timothycrosley/isort
  license: MIT
  license_file:
    - LICENSE
    - isort/_vendored/tomli/LICENSE
  summary: A Python utility / library to sort Python imports.
  description: |
    isort is a Python utility / library to sort imports alphabetically, and
    automatically separated into sections. It provides a command line utility,
    Python library and plugins for various editors to quickly sort all your
    imports. It currently cleanly supports Python 2.6 - 3.5 using pies to
    achieve this without ugly hacks and/or py2to3.
  doc_url: http://isort.readthedocs.io/en/latest/
  doc_source_url: https://github.com/timothycrosley/isort/blob/develop/README.rst
  dev_url: https://github.com/timothycrosley/isort

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
    - nehaljwani
    - ocefpaf
